name: OHW
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pangeo-notebook=2021.07.24
  - argopy
  - bokeh
  - bottleneck
  - cartopy
  - cdsapi
  - cf-units
  - cf_xarray
  - cmip6_preprocessing
  - colorcet
  - compilers
  - compliance-checker
  - cotede
  - ctd
  - dask
  - datashader
  - descartes
  - erddapy
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  - intake
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - oceansdb
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - s3fs
  - scipy
  - seaborn
  - seawater
  - shapely
  - siphon
  - xarray
  - xlrd
  - zarr
  # R packages
  - r-base
  - r-ape
  - r-cowplot
  - r-crul
  - r-gridextra
  - r-gsw
  - r-irkernel
  - r-leaflet
  - r-mapdata
  - r-maps
  - r-maptools
  - r-ncdf4
  - r-patchwork
  - r-plotly
  - r-raster
  - r-rastervis
  - r-remotes
  - r-rgdal
  - r-rgeos
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-sf
  - r-tidyverse
  - r-vegan
  - rpy2
  # robis deps
  - r-commonmark
  - r-dplyr
  - r-ggplot2
  - r-httpcache
  - r-httr
  - r-jsonlite
  - r-leaflet
  - r-mapedit
  - r-robis
  - r-tibble
  - r-tidyr
  - r-rlang
  - r-sf
  - r-oce
  # r-oce Suggests
  - r-akima
  - r-automap
  - r-dbi
  - r-foreign
  - r-knitr
  - r-lubridate
  # - r-marmap :: https://github.com/conda-forge/staged-recipes/pull/15763
  - r-ncdf4
  # - r-ocedata :: https://github.com/conda-forge/staged-recipes/pull/15763
  - r-raster >=1.4.3
  - r-rgeos
  - r-rmarkdown
  - r-rsqlite
  - r-r.utils
  - r-sp
  - r-tiff
  - r-xml2

  # extras
  - conda-lock
  - git
  - graphviz
